export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1>This is Header</h1>
        </header>
        {children}
        <footer>
          <h2>This is footer </h2>
          </footer>
          </body>
    </html>
  )
}
